trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    jobs:
      - job: create_Repo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'

        