trigger: none

pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    variables:
     - group: access-tokens
    jobs:
      - job: create_Repo
        steps:
        - checkout: self
          persistCredentials: true
          
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'        
              echo $(my-name)

        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: |
              name="tf-deploy-crm-data-migration"
              myList = name.split("-")
              finalKeyword = ""
              for words in myList[1:]:
                  finalKeyword += words[0]
              print('##vso[task.setvariable variable=shortendName;]'+finalKeyword)
    
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              set -x
              curl -L -s -o ./jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x ./jq
              content=$( curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer $(api-token)' --header 'Content-Type: application/json' --data-raw '{ "name": "${{ parameters.RepoName }}" } ' )
              clone_url_response= echo $content | jq .clone_url
          enabled: false
              
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo $(clone_url_response)
              git config --global user.email "$(Build.RequestedForEmail)"
              git config --global user.name "$(Build.QueuedBy)"
              cd Template-Repo
              git init
              git add .
              git commit -m "Commit made from pipeline"
              ls
              git push https://$(api-token)@github.com/Harshwardhan-Deshmukh/${{ parameters.RepoName }}.git 
          enabled: false
          
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo $(shortendName)
              
 