trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    jobs:
      - job: create_Repo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              set -x
              curl -L -s -o ./jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x ./jq
              content=$( curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer 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' --header 'Content-Type: application/json' --data-raw '{ "name": "${{ parameters.RepoName }}" } ' ) 
              echo $content

        