trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    variables:
      groups: access-tokens
    jobs:
      - job: create_Repo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer $(api-token)' --header 'Content-Type: application/json' --data-raw '{ "name": "${{ parameters.RepoName }}" } ' 
              

        