trigger: none

pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    variables:
     - group: access-tokens
    jobs:
      - job: create_Repo
        steps:
        - checkout: self
          persistCredentials: true
          
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'        
              echo $(my-name)
    
        - task: Bash@3
          displayName: Creating Empty Repository
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              set -x
              curl -L -s -o ./jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x ./jq
              content=$( curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer $(api-token)' --header 'Content-Type: application/json' --data-raw '{ "name": "${{ parameters.RepoName }}" } ' )
              clone_url_response= echo $content | jq .clone_url

              
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: |
              import os
              os.mkdir(os. getcwd()+"/Template-Repo/environments/")
            

        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: |
              import os
              workingDirectory = os. getcwd()+"/Template-Repo/environments/"
              backendPath = workingDirectory + "sit"
              backendFile = 'backend.tf'
              os.mkdir(backendPath)
              if os.path.exists(os.path.join(backendPath, backendFile)):
                  print('file already exists')
              else: 
                  fp = open(os.path.join(backendPath, backendFile), 'x')
                  fp.close()
              envVarsFile = 'environment.tfvars'        
              if os.path.exists(os.path.join(backendPath, envVarsFile)):
                  print('file already exists')
              else:
                  fp = open(os.path.join(backendPath, envVarsFile), 'x')
                  fp.close()
              
              print(os.getcwd())
        
        - task: PythonScript@0
          displayName: Add environment Vars file
          inputs:
            scriptSource: 'inline'
            script: |
              import os
              workingDirectory = os. getcwd()+"/Template-Repo/environments/"
              environmentValue = "sit"
              backendPath = workingDirectory + environmentValue
              envVarsFile = 'environment.tfvars'
              with open(os.path.join(backendPath, envVarsFile), "a") as file_Object:
                  file_Object.write('environment \t\t = "'+ environmentValue +'"\n')
          
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: |
              import os, sys
              name=sys.argv[1]
              myList = name.split("-")
              finalKeyword = ""
              for words in myList[1:]:
                  finalKeyword += words[0]
              workingDirectory = os. getcwd()+"/Template-Repo/environments/"
              environmentValue = "sit"
              backendPath = workingDirectory + environmentValue
              backendFile = 'backend.tf'
              
              # Add resource group
              with open(os.path.join(backendPath, backendFile), "a") as file_Object:
                  file_Object.write('resource_group_name \t = "psecom-terraform-'+environmentValue+'-rg-01"\n')
              
              # Add storage account name
              with open(os.path.join(backendPath, backendFile), "a") as file_Object:
                  file_Object.write('storage_account_name \t = "psecomtf'+environmentValue+'uksst01"\n')
              
              # Add storage account name
              with open(os.path.join(backendPath, backendFile), "a") as file_Object:
                  file_Object.write('container \t\t = "terraform"\n')
              
              # # Add key
              with open(os.path.join(backendPath, backendFile), "a") as file_Object:
                  file_Object.write('key \t\t\t = "' + finalKeyword + '-dev"')
            arguments: '${{ parameters.RepoName }}'

        - task: Bash@3
          displayName: Pushing Changes to the repository
          inputs:
            targetType: 'inline'
            script: |
              git config --global user.email "$(Build.RequestedForEmail)"
              git config --global user.name "$(Build.QueuedBy)"
              cd Template-Repo
              git init
              git add .
              git commit -m "Initialized a Terraform Template Repository"
              ls
              git branch -a
              git push --set-upstream https://$(api-token)@github.com/Harshwardhan-Deshmukh/${{ parameters.RepoName }}.git master
              git log -a
          
        
              
 