trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: RepoName
  displayName: Repository Name
  type: string
  default: 'Test_Repo_$(Build.BuildId)'

stages:
  - stage: GitHub_API
    variables:
     - group: access-tokens
    jobs:
      - job: create_Repo
        steps:
        - checkout: self
          persistCredentials: true
          
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo '${{ parameters.RepoName }} is created'        
              echo $(my-name)
    
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              set -x
              curl -L -s -o ./jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x ./jq
              content=$( curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer $(api-token)' --header 'Content-Type: application/json' --data-raw '{ "name": "${{ parameters.RepoName }}" } ' )
              clone_url_response= echo $content | jq .clone_url
              
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo $(clone_url_response)
              git clone https://$(api-token)@github.com/Harshwardhan-Deshmukh/gs-spring-boot.git
              git config --global user.email "$(Build.RequestedForEmail)"
              git config --global user.name "$(Build.QueuedBy)"
              cd gs-spring-boot
              git pull origin master
              git add .
              git commit -m "Commit made from pipeline"
              ls
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: |
              from urllib.parse import urlparse
              url = '$(clone_url_response)'
              parse_object = urlparse(url)
              domain=parse_object.netloc
              path=parse_object.path
              protocol=parse_object.scheme
              api_token=$(api-token)
              final_url=protocol+"://"+api_token+"@"+domain+path
              print( echo "##vso[task.setvariable variable=clone_link]final_url")

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'echo $(clone_link)'


        

        