# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: create_repo
    jobs:
      - job: create_repo
        steps:
          - checkout: self
            persistCredentials: true
       
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
               #!/bin/bash
               gh auth login
               gh api -H "Accept: application/vnd.github+json" /users/yvnsraviteja1729/repos

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                gh repo create anonymous-repo --private
                git config --global user.email "harshwardhanet7007@gmail.com"
                git config --global user.name "Harshwardhan"
                git config --global init.defaultBranch main
                # gh repo clone https://github.com/Harshwardhan-Deshmukh/my-project
                cd Template-Repo
                git init
                git remote add origin https://github.com/Harshwardhan-Deshmukh/my-project.git
                git add .
                git commit -m "Initialized a Terraform Template Repository"
                git push -u origin main
              #  set -x
              #  curl -L -s -o ./jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              #  chmod +x ./jq
              #  runid=$( curl --location --request POST 'https://api.github.com/user/repos' --header 'Authorization: Bearer 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' --header 'Content-Type: application/json' --data-raw '{ "name": "Demo3-Repo" } ' )